name: Build Axis Linux ISO
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check the environments CPU
        run: |
          lscpu | grep "Model name"

      - name: Install packages via pacman
        run: |
          pacman -Syu arch-install-scripts archiso git base-devel wget --noconfirm --needed
          
      - name: Install Axis Linux on top of Arch Linux
        run: |
          wget -O axislinux-key https://raw.githubusercontent.com/axislinux/releases-nightly/master/axislinux-key
          pacman-key --init
          pacman-key -a axislinux-key
          pacman-key --lsign-key FD11A3293A6830E6D28E1408A182D760A59FDFDD
          rm /etc/pacman.conf
          wget -O /etc/pacman.conf https://raw.githubusercontent.com/axislinux/axis-live/master/axislive/pacman.conf
          pacman -Syu --noconfirm
      
      - name: Download Axis Linux build files
        run: |
          git clone https://github.com/axislinux/axis-live
          sed -i 's/iso_name="axislinux"/iso_name="axislinux-NIGHTLY"/g' axis-live/axislive/profiledef.sh
      
      - name: Build Axis Linux ISO
        run: |
          cd axis-live
          mkarchiso -v axislive
          
      - name: Clean up work directory
        run: |
          rm -rf axis-live/work
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      
      - name: Download RELEASE.md
        run: |
          wget -O RELEASE.md https://raw.githubusercontent.com/axislinux/releases-nightly/master/RELEASE.md

      - name: Create a Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.date.outputs.date }}-NIGHTLY
          tag_prefix: 

      - name: Publish a Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.date.outputs.date }}-NIGHTLY
          files: axis-live/out/axislinux*
          body_path: RELEASE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
